export enum Icons {
  attachments = 'ATTACHMENTS',
  addplus = 'ADDPLUS',
  remove = 'REMOVE',
  calender = 'CALENDER',
  cicle = 'CIRCLE',
  cross = 'CROSS',
  downarrow = 'DOWNARROW',
  download = 'DOWNLOAD',
  ellipse = 'ELLIPSE',
  filter = 'FILTER',
  history = 'HISTORY',
  left = 'LEFT',
  play = 'PLAY',
  right = 'RIGHT',
  tickthick = 'THICKTICK',
  tick = 'TICK',
  uparrow = 'UPARROW',
  user = 'USER',
  vector = 'VECTOR',
  vectorone = 'VECTORONE',
  success = 'SUCCESS',
  alert = 'ALERT',
  more = 'MORE',
  checkboxUnchecked = 'CHECKBOXUNCHECKED',
  checkboxChecked = 'CHECKBOXCHECKED',
}
